/// Translations of the catalog feature.
class CatalogLanguages {
  const CatalogLanguages._();

  static const Map<String, dynamic> es = <String, dynamic>{
    'catalog': <String, dynamic>{
      'categories': <String, dynamic>{
        'car': 'Carros',
        'motorcycle': 'Motos',
        'scooter': 'Patinetas',
        'bicycle': 'Bicicletas',
        'truck': 'Camionetas',
      },
      'conditions': <String, dynamic>{'new': 'Nuevo', 'used': 'Usado'},
      'statuses': <String, dynamic>{
        'active': 'Activa',
        'paused': 'Pausada',
        'deleted': 'Eliminada',
      },
      'sorts': <String, dynamic>{
        'recent': 'Más recientes',
        'price_asc': 'Precio: menor a mayor',
        'price_desc': 'Precio: mayor a menor',
        'best_rated': 'Mejor calificados',
      },
      'list': <String, dynamic>{
        'title': 'Catálogo',
        'search_hint': 'Busca vehículos…',
        'results_count': '{count} resultados',
        'empty_title': 'Sin resultados',
        'empty_message':
            'No hay productos que coincidan con tu búsqueda o filtros.',
        'error_title': 'No pudimos cargar el catálogo',
        'retry_button': 'Reintentar',
        'filters_title': 'Filtros',
        'category_label': 'Categoría',
        'condition_label': 'Condición',
        'price_range_label': 'Rango de precio',
        'only_in_stock': 'Solo con stock',
        'clear_filters': 'Limpiar filtros',
        'sort_label': 'Ordenar por',
        'stock_label': 'Stock: {count}',
        'out_of_stock': 'Sin stock',
        'filter_price_chip': 'Precio',
        'filter_stock_chip': 'Con stock',
      },
      'detail': <String, dynamic>{
        'title': 'Detalle',
        'description_label': 'Descripción',
        'seller_label': 'Vendido por',
        'reviews_title': 'Reseñas',
        'no_reviews': 'Este producto aún no tiene reseñas.',
        'quantity_label': 'Cantidad',
        'add_to_cart_button': 'Agregar al carrito',
        'out_of_stock_cta': 'Sin stock disponible',
        'added_to_cart': 'Agregado al carrito',
        'add_to_cart_error': 'No se pudo agregar al carrito',
        'link_copied': 'Enlace copiado al portapapeles',
        'share_label': 'Compartir',
        'favorite_label': 'Favorito',
        'edit_button': 'Editar publicación',
        'own_product_notice': 'Esta publicación es tuya.',
        'write_review_button': 'Escribir reseña',
        'edit_review_button': 'Editar mi reseña',
        'not_found_title': 'Producto no encontrado',
        'not_found_message':
            'La publicación no existe o fue eliminada por su dueño.',
        'error_title': 'No pudimos cargar el producto',
        'retry_button': 'Reintentar',
      },
      'form': <String, dynamic>{
        'create_title': 'Publicar producto',
        'edit_title': 'Editar publicación',
        'name_label': 'Nombre (3–60)',
        'description_label': 'Descripción (10–500)',
        'price_label': 'Precio',
        'stock_label': 'Stock',
        'category_label': 'Categoría',
        'condition_label': 'Condición',
        'image_label': 'Imagen (opcional)',
        'pick_image_button': 'Elegir imagen',
        'save_button': 'Guardar publicación',
        'name_invalid': 'El nombre debe tener entre 3 y 60 caracteres',
        'description_invalid':
            'La descripción debe tener entre 10 y 500 caracteres',
        'price_invalid': 'Ingresa un precio mayor que 0',
        'stock_invalid': 'Ingresa un stock válido (0 o más)',
        'save_error': 'No se pudo guardar la publicación',
        'discard_title': 'Descartar cambios',
        'discard_message': 'Tienes cambios sin guardar. ¿Quieres salir?',
        'discard_confirm': 'Salir sin guardar',
        'discard_cancel': 'Seguir editando',
        'not_found_title': 'Publicación no encontrada',
        'error_title': 'No pudimos preparar el formulario',
        'retry_button': 'Reintentar',
      },
      'my_products': <String, dynamic>{
        'title': 'Mis publicaciones',
        'empty_title': 'Aún no has publicado',
        'empty_message': 'Publica tu primer vehículo para venderlo aquí.',
        'publish_button': 'Publicar producto',
        'error_title': 'No pudimos cargar tus publicaciones',
        'retry_button': 'Reintentar',
        'pause_button': 'Pausar',
        'activate_button': 'Reactivar',
        'delete_button': 'Eliminar',
        'delete_title': 'Eliminar publicación',
        'delete_message':
            'La publicación desaparecerá del catálogo. Las órdenes históricas la conservan.',
        'confirm': 'Eliminar',
        'cancel': 'Cancelar',
        'stock_label': 'Stock',
      },
      'favorites': <String, dynamic>{
        'title': 'Favoritos',
        'empty_title': 'Sin favoritos todavía',
        'empty_message': 'Marca el corazón de un producto para guardarlo aquí.',
        'error_title': 'No pudimos cargar tus favoritos',
        'retry_button': 'Reintentar',
        'move_to_cart_button': 'Mover al carrito',
        'move_all_button': 'Mover todo al carrito',
        'moved_one': 'Producto movido al carrito',
        'moved_many': '{count} productos movidos al carrito',
        'out_of_stock_notice': 'Sin stock',
        'removed_by_owner_notice': 'Ya no disponible',
      },
      'review_form': <String, dynamic>{
        'title': 'Tu reseña',
        'rating_label': 'Calificación',
        'comment_label': 'Comentario (opcional, máx. 300)',
        'submit_button': 'Guardar reseña',
        'save_error': 'No se pudo guardar la reseña',
        'cannot_title': 'Aún no puedes reseñar',
        'cannot_message':
            'Solo puedes calificar productos que compraste y ya fueron entregados.',
        'error_title': 'No pudimos preparar la reseña',
        'retry_button': 'Reintentar',
      },
    },
  };

  static const Map<String, dynamic> en = <String, dynamic>{
    'catalog': <String, dynamic>{
      'categories': <String, dynamic>{
        'car': 'Cars',
        'motorcycle': 'Motorcycles',
        'scooter': 'Scooters',
        'bicycle': 'Bicycles',
        'truck': 'Trucks',
      },
      'conditions': <String, dynamic>{'new': 'New', 'used': 'Used'},
      'statuses': <String, dynamic>{
        'active': 'Active',
        'paused': 'Paused',
        'deleted': 'Deleted',
      },
      'sorts': <String, dynamic>{
        'recent': 'Newest',
        'price_asc': 'Price: low to high',
        'price_desc': 'Price: high to low',
        'best_rated': 'Best rated',
      },
      'list': <String, dynamic>{
        'title': 'Catalog',
        'search_hint': 'Search vehicles…',
        'results_count': '{count} results',
        'empty_title': 'No results',
        'empty_message': 'No products match your search or filters.',
        'error_title': 'We could not load the catalog',
        'retry_button': 'Retry',
        'filters_title': 'Filters',
        'category_label': 'Category',
        'condition_label': 'Condition',
        'price_range_label': 'Price range',
        'only_in_stock': 'In stock only',
        'clear_filters': 'Clear filters',
        'sort_label': 'Sort by',
        'stock_label': 'Stock: {count}',
        'out_of_stock': 'Out of stock',
        'filter_price_chip': 'Price',
        'filter_stock_chip': 'In stock',
      },
      'detail': <String, dynamic>{
        'title': 'Detail',
        'description_label': 'Description',
        'seller_label': 'Sold by',
        'reviews_title': 'Reviews',
        'no_reviews': 'This product has no reviews yet.',
        'quantity_label': 'Quantity',
        'add_to_cart_button': 'Add to cart',
        'out_of_stock_cta': 'Out of stock',
        'added_to_cart': 'Added to cart',
        'add_to_cart_error': 'Could not add to cart',
        'link_copied': 'Link copied to clipboard',
        'share_label': 'Share',
        'favorite_label': 'Favorite',
        'edit_button': 'Edit publication',
        'own_product_notice': 'This publication is yours.',
        'write_review_button': 'Write a review',
        'edit_review_button': 'Edit my review',
        'not_found_title': 'Product not found',
        'not_found_message':
            'The publication does not exist or was removed by its owner.',
        'error_title': 'We could not load the product',
        'retry_button': 'Retry',
      },
      'form': <String, dynamic>{
        'create_title': 'Publish product',
        'edit_title': 'Edit publication',
        'name_label': 'Name (3–60)',
        'description_label': 'Description (10–500)',
        'price_label': 'Price',
        'stock_label': 'Stock',
        'category_label': 'Category',
        'condition_label': 'Condition',
        'image_label': 'Image (optional)',
        'pick_image_button': 'Pick image',
        'save_button': 'Save publication',
        'name_invalid': 'Name must be between 3 and 60 characters',
        'description_invalid':
            'Description must be between 10 and 500 characters',
        'price_invalid': 'Enter a price greater than 0',
        'stock_invalid': 'Enter a valid stock (0 or more)',
        'save_error': 'The publication could not be saved',
        'discard_title': 'Discard changes',
        'discard_message': 'You have unsaved changes. Leave anyway?',
        'discard_confirm': 'Leave without saving',
        'discard_cancel': 'Keep editing',
        'not_found_title': 'Publication not found',
        'error_title': 'We could not prepare the form',
        'retry_button': 'Retry',
      },
      'my_products': <String, dynamic>{
        'title': 'My publications',
        'empty_title': 'Nothing published yet',
        'empty_message': 'Publish your first vehicle to sell it here.',
        'publish_button': 'Publish product',
        'error_title': 'We could not load your publications',
        'retry_button': 'Retry',
        'pause_button': 'Pause',
        'activate_button': 'Reactivate',
        'delete_button': 'Delete',
        'delete_title': 'Delete publication',
        'delete_message':
            'It will disappear from the catalog. Historical orders keep it.',
        'confirm': 'Delete',
        'cancel': 'Cancel',
        'stock_label': 'Stock',
      },
      'favorites': <String, dynamic>{
        'title': 'Favorites',
        'empty_title': 'No favorites yet',
        'empty_message': 'Tap the heart on a product to save it here.',
        'error_title': 'We could not load your favorites',
        'retry_button': 'Retry',
        'move_to_cart_button': 'Move to cart',
        'move_all_button': 'Move all to cart',
        'moved_one': 'Product moved to cart',
        'moved_many': '{count} products moved to cart',
        'out_of_stock_notice': 'Out of stock',
        'removed_by_owner_notice': 'No longer available',
      },
      'review_form': <String, dynamic>{
        'title': 'Your review',
        'rating_label': 'Rating',
        'comment_label': 'Comment (optional, max 300)',
        'submit_button': 'Save review',
        'save_error': 'The review could not be saved',
        'cannot_title': 'You cannot review yet',
        'cannot_message':
            'You can only rate products you bought that were delivered.',
        'error_title': 'We could not prepare the review',
        'retry_button': 'Retry',
      },
    },
  };
}
