/// Translations of the cart feature.
class CartLanguages {
  const CartLanguages._();

  static const Map<String, dynamic> es = <String, dynamic>{
    'cart': <String, dynamic>{
      'payment_methods': <String, dynamic>{
        'card': 'Tarjeta',
        'cash': 'Efectivo',
        'transfer': 'Transferencia',
      },
      'coupon_errors': <String, dynamic>{
        'not_found': 'El cupón no existe',
        'expired': 'El cupón está vencido',
        'inactive': 'El cupón no está activo',
        'min_amount_not_reached': 'El total no alcanza el mínimo del cupón',
      },
      'errors': <String, dynamic>{
        'out_of_stock': 'Un producto del carrito ya no tiene stock suficiente',
        'empty_cart': 'El carrito está vacío',
      },
      'home': <String, dynamic>{
        'title': 'Carrito',
        'empty_title': 'Tu carrito está vacío',
        'empty_message': 'Explora el catálogo y agrega productos.',
        'go_to_catalog_button': 'Ir al catálogo',
        'error_title': 'No pudimos cargar tu carrito',
        'retry_button': 'Reintentar',
        'remove_item': 'Quitar del carrito',
        'item_removed': 'Producto quitado del carrito',
        'undo_button': 'Deshacer',
        'unavailable_notice': 'Sin stock suficiente o no disponible',
        'coupon_label': 'Cupón de descuento',
        'apply_coupon_button': 'Aplicar',
        'remove_coupon_button': 'Quitar cupón',
        'coupon_applied': 'Cupón {code}: -{pct}%',
        'subtotal_label': 'Subtotal',
        'discount_label': 'Descuento',
        'tax_label': 'IVA (19%)',
        'total_label': 'Total',
        'clear_cart_button': 'Vaciar carrito',
        'clear_cart_title': 'Vaciar carrito',
        'clear_cart_message': 'Se quitarán todos los productos del carrito.',
        'confirm': 'Vaciar',
        'cancel': 'Cancelar',
        'checkout_button': 'Continuar la compra',
      },
      'checkout': <String, dynamic>{
        'title': 'Finalizar compra',
        'step_delivery': 'Entrega',
        'step_payment': 'Pago',
        'step_summary': 'Resumen',
        'choose_address': 'Elige una dirección de entrega',
        'no_addresses': 'Aún no tienes direcciones. Crea una para continuar.',
        'add_address_button': 'Nueva dirección',
        'address_label': 'Etiqueta (Casa, Oficina…)',
        'address_line1': 'Dirección',
        'address_city': 'Ciudad',
        'address_state': 'Departamento',
        'address_notes': 'Notas (opcional)',
        'address_save_button': 'Guardar dirección',
        'choose_payment': 'Elige el método de pago',
        'card_number_label': 'Número de tarjeta (16 dígitos)',
        'card_holder_label': 'Titular',
        'card_expiry_label': 'Vencimiento (MM/AA)',
        'card_cvv_label': 'CVV',
        'card_number_invalid': 'Ingresa los 16 dígitos de la tarjeta',
        'card_expiry_invalid': 'Formato MM/AA',
        'card_cvv_invalid': '3 o 4 dígitos',
        'card_disclaimer':
            'Pago simulado: los datos de la tarjeta no se guardan.',
        'summary_items': 'Productos',
        'summary_address': 'Entrega',
        'summary_payment': 'Pago',
        'summary_totals': 'Totales',
        'next_button': 'Siguiente',
        'back_button': 'Atrás',
        'confirm_button': 'Confirmar compra',
        'confirm_error': 'No se pudo completar la compra',
        'error_title': 'No pudimos preparar el checkout',
        'retry_button': 'Reintentar',
      },
      'success': <String, dynamic>{
        'title': 'Compra exitosa',
        'headline': '¡Gracias por tu compra!',
        'order_number': 'Orden {number}',
        'body': 'Puedes seguir el estado de tu orden en el historial.',
        'go_to_order_button': 'Ver orden',
        'go_to_home_button': 'Ir al inicio',
      },
    },
  };

  static const Map<String, dynamic> en = <String, dynamic>{
    'cart': <String, dynamic>{
      'payment_methods': <String, dynamic>{
        'card': 'Card',
        'cash': 'Cash',
        'transfer': 'Transfer',
      },
      'coupon_errors': <String, dynamic>{
        'not_found': 'The coupon does not exist',
        'expired': 'The coupon has expired',
        'inactive': 'The coupon is not active',
        'min_amount_not_reached': 'The total does not reach the coupon minimum',
      },
      'errors': <String, dynamic>{
        'out_of_stock': 'A product in the cart no longer has enough stock',
        'empty_cart': 'The cart is empty',
      },
      'home': <String, dynamic>{
        'title': 'Cart',
        'empty_title': 'Your cart is empty',
        'empty_message': 'Browse the catalog and add products.',
        'go_to_catalog_button': 'Go to catalog',
        'error_title': 'We could not load your cart',
        'retry_button': 'Retry',
        'remove_item': 'Remove from cart',
        'item_removed': 'Product removed from cart',
        'undo_button': 'Undo',
        'unavailable_notice': 'Not enough stock or unavailable',
        'coupon_label': 'Discount coupon',
        'apply_coupon_button': 'Apply',
        'remove_coupon_button': 'Remove coupon',
        'coupon_applied': 'Coupon {code}: -{pct}%',
        'subtotal_label': 'Subtotal',
        'discount_label': 'Discount',
        'tax_label': 'VAT (19%)',
        'total_label': 'Total',
        'clear_cart_button': 'Empty cart',
        'clear_cart_title': 'Empty cart',
        'clear_cart_message': 'All products will be removed from the cart.',
        'confirm': 'Empty',
        'cancel': 'Cancel',
        'checkout_button': 'Proceed to checkout',
      },
      'checkout': <String, dynamic>{
        'title': 'Checkout',
        'step_delivery': 'Delivery',
        'step_payment': 'Payment',
        'step_summary': 'Summary',
        'choose_address': 'Choose a delivery address',
        'no_addresses': 'You have no addresses yet. Create one to continue.',
        'add_address_button': 'New address',
        'address_label': 'Label (Home, Office…)',
        'address_line1': 'Address line',
        'address_city': 'City',
        'address_state': 'State',
        'address_notes': 'Notes (optional)',
        'address_save_button': 'Save address',
        'choose_payment': 'Choose the payment method',
        'card_number_label': 'Card number (16 digits)',
        'card_holder_label': 'Card holder',
        'card_expiry_label': 'Expiry (MM/YY)',
        'card_cvv_label': 'CVV',
        'card_number_invalid': 'Enter the 16 card digits',
        'card_expiry_invalid': 'MM/YY format',
        'card_cvv_invalid': '3 or 4 digits',
        'card_disclaimer': 'Simulated payment: card data is never stored.',
        'summary_items': 'Items',
        'summary_address': 'Delivery',
        'summary_payment': 'Payment',
        'summary_totals': 'Totals',
        'next_button': 'Next',
        'back_button': 'Back',
        'confirm_button': 'Confirm purchase',
        'confirm_error': 'The purchase could not be completed',
        'error_title': 'We could not prepare the checkout',
        'retry_button': 'Retry',
      },
      'success': <String, dynamic>{
        'title': 'Purchase complete',
        'headline': 'Thanks for your purchase!',
        'order_number': 'Order {number}',
        'body': 'You can track your order from the history.',
        'go_to_order_button': 'View order',
        'go_to_home_button': 'Go home',
      },
    },
  };
}
