/// Translations of the profile feature.
class ProfileLanguages {
  const ProfileLanguages._();

  static const Map<String, dynamic> es = <String, dynamic>{
    'profile': <String, dynamic>{
      'home': <String, dynamic>{
        'title': 'Perfil',
        'edit_button': 'Editar perfil',
        'name_label': 'Nombre completo',
        'phone_label': 'Teléfono',
        'avatar_button': 'Cambiar avatar',
        'save_button': 'Guardar cambios',
        'cancel_button': 'Cancelar',
        'saved_message': 'Perfil actualizado',
        'save_error': 'No se pudo guardar',
        'security_title': 'Seguridad de la cuenta',
        'change_password_button': 'Cambiar contraseña',
        'current_password_label': 'Contraseña actual',
        'new_password_label': 'Nueva contraseña',
        'confirm_new_password_label': 'Confirmar nueva contraseña',
        'submit_password_button': 'Actualizar contraseña',
        'password_changed_message': 'Contraseña actualizada',
        'addresses_button': 'Mis direcciones',
        'settings_button': 'Ajustes',
        'logout_button': 'Cerrar sesión',
        'logout_title': 'Cerrar sesión',
        'logout_message':
            'Tu carrito y tus órdenes se conservan para la próxima vez.',
        'confirm': 'Confirmar',
        'cancel': 'Cancelar',
        'danger_title': 'Zona de riesgo',
        'delete_account_button': 'Eliminar mi cuenta',
        'delete_account_title': 'Eliminar cuenta',
        'delete_account_message':
            'Se borrarán tu perfil, direcciones, carrito, favoritos, órdenes y notificaciones.',
        'delete_account_second_title': '¿Estás completamente seguro?',
        'delete_account_second_message':
            'Esta acción no se puede deshacer. Tus publicaciones desaparecerán del catálogo.',
      },
      'addresses': <String, dynamic>{
        'title': 'Mis direcciones',
        'add_button': 'Nueva dirección',
        'label_label': 'Etiqueta (Casa, Oficina…)',
        'line1_label': 'Dirección',
        'city_label': 'Ciudad',
        'state_label': 'Departamento',
        'notes_label': 'Notas (opcional)',
        'save_button': 'Guardar dirección',
        'default_badge': 'Predeterminada',
        'set_default_button': 'Usar como predeterminada',
        'edit_button': 'Editar',
        'delete_button': 'Eliminar',
        'delete_title': 'Eliminar dirección',
        'delete_message': 'Se eliminará esta dirección.',
        'confirm': 'Eliminar',
        'cancel': 'Cancelar',
        'error_in_use':
            'No se puede eliminar: una orden activa usa esta dirección.',
        'empty_title': 'Sin direcciones',
        'empty_message': 'Crea una dirección para usarla en el checkout.',
        'error_title': 'No pudimos cargar tus direcciones',
        'retry_button': 'Reintentar',
      },
    },
  };

  static const Map<String, dynamic> en = <String, dynamic>{
    'profile': <String, dynamic>{
      'home': <String, dynamic>{
        'title': 'Profile',
        'edit_button': 'Edit profile',
        'name_label': 'Full name',
        'phone_label': 'Phone',
        'avatar_button': 'Change avatar',
        'save_button': 'Save changes',
        'cancel_button': 'Cancel',
        'saved_message': 'Profile updated',
        'save_error': 'It could not be saved',
        'security_title': 'Account security',
        'change_password_button': 'Change password',
        'current_password_label': 'Current password',
        'new_password_label': 'New password',
        'confirm_new_password_label': 'Confirm new password',
        'submit_password_button': 'Update password',
        'password_changed_message': 'Password updated',
        'addresses_button': 'My addresses',
        'settings_button': 'Settings',
        'logout_button': 'Sign out',
        'logout_title': 'Sign out',
        'logout_message': 'Your cart and orders are kept for next time.',
        'confirm': 'Confirm',
        'cancel': 'Cancel',
        'danger_title': 'Danger zone',
        'delete_account_button': 'Delete my account',
        'delete_account_title': 'Delete account',
        'delete_account_message':
            'Your profile, addresses, cart, favorites, orders and notifications will be deleted.',
        'delete_account_second_title': 'Are you absolutely sure?',
        'delete_account_second_message':
            'This cannot be undone. Your publications will disappear from the catalog.',
      },
      'addresses': <String, dynamic>{
        'title': 'My addresses',
        'add_button': 'New address',
        'label_label': 'Label (Home, Office…)',
        'line1_label': 'Address line',
        'city_label': 'City',
        'state_label': 'State',
        'notes_label': 'Notes (optional)',
        'save_button': 'Save address',
        'default_badge': 'Default',
        'set_default_button': 'Set as default',
        'edit_button': 'Edit',
        'delete_button': 'Delete',
        'delete_title': 'Delete address',
        'delete_message': 'This address will be deleted.',
        'confirm': 'Delete',
        'cancel': 'Cancel',
        'error_in_use':
            'It cannot be deleted: an active order uses this address.',
        'empty_title': 'No addresses',
        'empty_message': 'Create an address to use it at checkout.',
        'error_title': 'We could not load your addresses',
        'retry_button': 'Retry',
      },
    },
  };
}
